---
title: "Plot F0"
date: "30/06/2020"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_minimal())
library(zoo)
```

# Read data

```{r f0}
f0 <- readRDS("./data/dataframes/f0.rds") %>%
  mutate(repetition = as.factor(repetition))
```

# Plot f0

```{r all}
# all speakers and sentence types together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = speaker, shape = sentence)) +
  geom_point(alpha = 0.2) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  )
```

```{r by-sentence, out.width="200%"}
# per sentence type, speakers together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = speaker, shape = repetition)) +
  geom_point(alpha = 0.5) +
  geom_path() +
  facet_wrap( ~ sentence) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  theme(legend.pos = "bottom")
```

```{r by-token, fig.height=7, out.width="200%"}
# per sentence type, speakers together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = speaker)) +
  geom_point(size = 0.5) +
  facet_grid(speaker + repetition ~ sentence) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  theme(legend.pos = "bottom")
```

```{r by-token-smoothed, fig.height=7, out.width="200%"}
f0 %>%
  group_by(token) %>%
  mutate(f0_smooth = c(rep(NA, 10), rollmean(f0, 21), rep(NA, 10))) %>%
  ggplot(aes(norm_timepoint, f0_smooth, colour = speaker)) +
  geom_point(size = 0.5) +
  facet_grid(speaker + repetition ~ sentence) +
  labs(
    title = "Smoothed f0 contours",
    caption = "Rolling mean filter, order = 21",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  theme(legend.pos = "bottom")
```
```{r f0-illustr, fig.height=7, out.width="200%"}
f0 %>%
  group_by(token) %>%
  mutate(f0_smooth = c(rep(NA, 10), rollmean(f0, 21), rep(NA, 10))) %>%
  filter(
    repetition == 2,
    speaker == "s01" & sentence_type == "narrow-focus" |
    speaker == "s01" & sentence_type == "polar-q" |
    speaker == "s04" & sentence_type == "broad-focus" |
    speaker == "s04" & sentence_type == "narrow-focus-q"
  ) %>%
  ggplot(aes(norm_timepoint, f0_smooth, colour = speaker)) +
  geom_point(size = 0.5) +
  facet_grid(. ~ sentence) +
  labs(
    title = "Smoothed f0 contours",
    caption = "Rolling mean filter, order = 21",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  theme(legend.pos = "bottom")
```

```{r by-speaker, out.width="200%"}
# per speaker, sentences together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = sentence, shape = repetition)) +
  facet_wrap(~speaker, nrow = 3) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  )
```

```{r by-sentence-speaker}
# per sentence and speaker ----
f0 %>%
  filter(speaker == "s01") %>%
  ggplot(aes(norm_timepoint, f0, colour = repetition)) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s01",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s02") %>%
  ggplot(aes(norm_timepoint, f0, colour = repetition)) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s02",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s04") %>%
  ggplot(aes(norm_timepoint, f0, colour = repetition)) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s04",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s05") %>%
  ggplot(aes(norm_timepoint, f0, colour = repetition)) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s05",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s06") %>%
  ggplot(aes(norm_timepoint, f0, colour = repetition)) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s06",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)
```

