---
title: "Fricatives CoG"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_bw())
```

```{r read-data}
fric_dft_l <- readRDS("./data/dataframes/fric_dtf_l.rds") %>%
  mutate(
    ipa = recode(labels, D = "ð", `T` = "θ", S = "ʃ", Z = "ʒ"),
    ipa = factor(ipa, levels = c("f", "θ", "s", "ʃ", "v", "ð", "z", "ʒ", "h"))
  )

cog <- readRDS("./data/dataframes/fric_moments.rds") %>%
  mutate(
    ipa = recode(labels, D = "ð", `T` = "θ", S = "ʃ", Z = "ʒ"),
    ipa = factor(ipa, levels = c("f", "θ", "s", "ʃ", "v", "ð", "z", "ʒ", "h"))
  )
```

# Averaged spectra

```{r average}
average_dft <- fric_dft_l %>%
  group_by(ipa, freq)%>%
  summarise(track_value = mean(track_value))
```

```{r spectra}
average_dft %>%
  filter(freq < 10000) %>%
  ggplot(aes(x = freq, y = track_value, colour = ipa)) +
  geom_line() +
  facet_wrap(~ ipa)
```

# Cog

```{r cog-plot}
cog %>%
  ggplot(aes(ipa, moment_1)) +
  geom_boxplot() +
  labs(
    x = element_blank(),
    y = "Center of gravity (Hz)"
  )

ggsave("./img/cog.png", width = 7, height = 5)
```

```{r means-sd}
cog %>%
  group_by(ipa) %>%
  summarise(mean = round(mean(moment_1), 0), sd = round(sd(moment_1), 0))
```

