---
title: "Plot formants and VOT"
date: "23/06/2020"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_bw())

revlog_trans <- function(base = exp(1)){
    ## Define the desired transformation.
    trans <- function(x){
                 -log(x, base)
                }
    ## Define the reverse of the desired transformation
    inv <- function(x){
                 base^(-x)
                }
    ## Creates the transformation
    trans_new(paste("revlog-", base, sep = ""),
              trans, ## The transformation function (can be defined using anonymous functions)
              inv,  ## The reverse of the transformation
              log_breaks(base = base), ## default way to define the scale breaks
              domain = c(1e-100, Inf) ## The domain over which the transformation is valued
             )
    }
```

```{r read-data}
formants <- readRDS("./data/dataframes/formants.rds") %>%
  mutate(vowel = factor(vowel, levels = c("i", "y", "u", "e", "@", "o", "a"))) %>%
  group_by(speaker) %>%
  mutate(
    F1.z = scale(F1),
    F2.z = scale(F2)
  ) %>%
  ungroup() %>%
  mutate(
    F1.z.hz = (F1.z * sd(F1)) + mean(F1),
    F2.z.hz = (F2.z * sd(F2)) + mean(F2)
  )

formants_all <- readRDS("./data/dataframes/formants_all.rds") %>%
  mutate(vowel = factor(vowel, levels = c("i", "y", "u", "e", "@", "o", "a")))

vot <- readRDS("./data/dataframes/vot.rds") %>%
  mutate(consonant =  factor(consonant, levels = c("g", "d", "b", "k", "t", "p")))
```

# Formants

```{r all}
# all speakers together
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="t", size=1)
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="norm", size=1)
```

```{r all-z}
# all speakers together, z-scored
centroids <- aggregate(cbind(F2.z,F1.z)~vowel, formants, mean) %>%
  mutate(ipa = c("i", "ÿ", "u", "e", "ɜ", "ɔ", "ä"))

formants %>%
  ggplot(aes(x = F2.z, y = F1.z, group = vowel)) +
  scale_x_reverse(name = "F2 (z-scores)", position = "top") +
  scale_y_reverse(name = "F1 (z-scores)", position = "right") +
  geom_point(aes(colour = vowel), alpha = 0.5) +
  stat_ellipse(aes(colour = vowel), type = "norm", size = 1) +
  geom_text(data = centroids, aes(V1, V2, label = ipa), size = 7) +
  theme(legend.position = "none") +
  scale_color_brewer(type = "qual", palette = 2)

ggsave("./img/vowel-plot.png", width = 7, height = 5)
```

```{r all-z-hz}
# all speakers together, z-scored
centroids <- aggregate(cbind(F2.z.hz,F1.z.hz)~vowel, formants, mean) %>%
  mutate(ipa = c("i", "ÿ", "u", "e", "ɜ", "ɔ", "ä"))

formants %>%
  ggplot(aes(x = F2.z.hz, y = F1.z.hz, group = vowel)) +
  scale_x_reverse(name = "F2 (norm Hz)", position = "top") +
  scale_y_reverse(name = "F1 (norm Hz)", position = "right") +
  geom_point(aes(colour = vowel), alpha = 0.5) +
  stat_ellipse(aes(colour = vowel), type = "norm", size = 1) +
  geom_text(data = centroids, aes(V1, V2, label = ipa), size = 7) +
  theme(legend.position = "none") +
  scale_color_brewer(type = "qual", palette = 2)

ggsave("./img/vowel-plot-z-hz.png", width = 7, height = 5)
```

```{r all-z-hz-log}
# all speakers together, z-scored
centroids <- aggregate(cbind(F2.z.hz,F1.z.hz)~vowel, formants, mean) %>%
  mutate(ipa = c("i", "ÿ", "u", "e", "ɜ", "ɔ", "ä"))

formants %>%
  ggplot(aes(x = F2.z.hz, y = F1.z.hz, group = vowel)) +
  scale_x_continuous(name = "F2 (norm Hz log)", position = "top", trans = revlog_trans(base = 2), breaks = seq(0, 3000, by = 250)) +
  scale_y_continuous(name = "F1 (norm Hz log)", position = "right", trans = revlog_trans(base = 2), breaks = seq(0, 3000, by = 250)) +
  geom_point(aes(colour = vowel), alpha = 0.5) +
  stat_ellipse(aes(colour = vowel), type = "norm", size = 1) +
  geom_text(data = centroids, aes(V1, V2, label = ipa), size = 7) +
  theme(legend.position = "none") +
  scale_color_brewer(type = "qual", palette = 2) +
  geom_abline(slope = 1, intercept = 0)

ggsave("./img/vowel-plot-z-hz-log.png", width = 7, height = 5)
```

```{r males}
# male speakers only
formants %>%
  filter(gender == "M") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="t", size=1)
formants %>%
  filter(gender == "M") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="norm", size=1)
```

```{r females}
# female speakers only
formants %>%
  filter(gender == "F") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="t", size=1)
formants %>%
  filter(gender == "F") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="norm", size=1)
```

```{r all-facet}
# male-female side by side
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  facet_wrap(~gender) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="t", size=1)
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  facet_wrap(~gender) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="norm", size=1)
```

```{r each}
# individual speakers side by side
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  facet_wrap(~speaker) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE)
```

## All vowels

```{r all-vowels-z}
formants_all %>%
  group_by(speaker) %>%
  mutate(
    F1_z = scale(F1),
    F2_z = scale(F2)
  ) %>%
  filter(
    F1_z < 2.5, F1_z > -2.5,
    F2_z < 2.5, F2_z > -2.5
  ) %>%
  ggplot(aes(F2_z, F1_z, colour = vowel, label = vowel)) +
  geom_point(alpha = 0.5) +
  stat_ellipse(type = "t") +
  scale_y_reverse() +
  scale_x_reverse() +
  coord_fixed()
```


# VOT

```{r vot-bar}
ggplot(vot, aes(x=VOT, y=consonant)) +
  stat_summary(fun = mean, geom = "bar") +
  stat_summary(fun.data = mean_se, geom = "errorbar", color="red")
```

```{r vot-dist}
vot %>%
  ggplot(aes(VOT)) +
  geom_density() +
  facet_wrap(. ~ consonant) + geom_rug()
```

```{r vot-jitter}
vot %>%
  ggplot(aes(consonant, VOT, colour = speaker, shape = speaker)) +
  geom_jitter(width = 0.25, size = 3.5, alpha = 0.7) +
  geom_hline(aes(yintercept = 0)) +
  coord_flip() +
  labs(
    y = "VOT (ms)"
  ) +
  scale_color_brewer(type = "qual", palette = 2)
ggsave("./img/vot-jitter.png", width = 7, height = 4)
```
