---
title: "Plot formants and VOT"
date: "23/06/2020"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_bw())
```

```{r read-data}
formants <- readRDS("./data/dataframes/formants.rds") %>%
  mutate(vowel = factor(vowel, levels = c("i", "y", "u", "e", "@", "o", "a")))

formants_all <- readRDS("./data/dataframes/formants_all.rds") %>%
  mutate(vowel = factor(vowel, levels = c("i", "y", "u", "e", "@", "o", "a")))

vot <- readRDS("./data/dataframes/vot.rds") %>%
  mutate(consonant =  factor(consonant, levels = c("g", "d", "b", "k", "t", "p")))
```

# Formants

```{r all}
# all speakers together
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="t", size=1)
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="norm", size=1)
```

```{r males}
# male speakers only
formants %>%
  filter(gender == "M") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="t", size=1)
formants %>%
  filter(gender == "M") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="norm", size=1)
```

```{r females}
# female speakers only
formants %>%
  filter(gender == "F") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="t", size=1)
formants %>%
  filter(gender == "F") %>%
  ggplot(aes(x=F2, y=F1, col=vowel)) +
    scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
    scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
    geom_text(aes(label=vowel), show.legend=FALSE) +
    stat_ellipse(type="norm", size=1)
```

```{r all-facet}
# male-female side by side
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  facet_wrap(~gender) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="t", size=1)
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  facet_wrap(~gender) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE) +
  stat_ellipse(type="norm", size=1)
```

```{r each}
# individual speakers side by side
ggplot(formants, aes(x=F2, y=F1, col=vowel)) +
  facet_wrap(~speaker) +
  scale_x_reverse(name="F2 (Hz)", limits = c(3500, 0)) +
  scale_y_reverse(name="F1 (Hz)", limits = c(1500, 0)) +
  geom_text(aes(label=vowel), show.legend=FALSE)
```

## All vowels

```{r all-vowels-z}
formants_all %>%
  group_by(speaker) %>%
  mutate(
    F1_z = scale(F1),
    F2_z = scale(F2)
  ) %>%
  filter(
    F1_z < 2.5, F1_z > -2.5,
    F2_z < 2.5, F2_z > -2.5
  ) %>%
  ggplot(aes(F2_z, F1_z, colour = vowel, label = vowel)) +
  geom_point(alpha = 0.5) +
  stat_ellipse(type = "t") +
  scale_y_reverse() +
  scale_x_reverse() +
  coord_fixed()
```


# VOT

```{r vot-bar}
ggplot(vot, aes(x=VOT, y=consonant)) +
  stat_summary(fun = mean, geom = "bar") +
  stat_summary(fun.data = mean_se, geom = "errorbar", color="red")
```

```{r vot-dist}
vot %>%
  ggplot(aes(VOT)) +
  geom_density() +
  facet_wrap(. ~ consonant) + geom_rug()
```

```{r vot-jitter}
vot %>%
  ggplot(aes(consonant, VOT, colour = speaker)) +
  geom_jitter(width = 0.2) +
  geom_hline(aes(yintercept = 0)) +
  coord_flip()
```
