---
title: "Plot F0"
date: "30/06/2020"
output: 
  html_document: 
    highlight: tango
    number_sections: yes
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_minimal())
```

# Read data

```{r f0}
f0 <- readRDS("./data/dataframes/f0.rds")
```

# Plot f0

```{r}
# all speakers and sentence types together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = speaker, shape = sentence)) +
  geom_point(alpha = 0.2) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  )
```

```{r}
# per sentence type, speakers together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = speaker, shape = as.factor(repetition))) +
  geom_point(alpha = 0.5, size = 0.5) +
  facet_wrap(~ sentence) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  )
```

```{r}
# per speaker, sentences together ----
f0 %>%
  ggplot(aes(norm_timepoint, f0, colour = sentence, shape = as.factor(repetition))) +
  facet_wrap(~speaker, nrow = 3) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    x = "f0 (Hz)",
    y = "normalised time"
  )
```

```{r}
# per sentence and speaker ----
f0 %>%
  filter(speaker == "s01") %>%
  ggplot(aes(norm_timepoint, f0, colour = as.factor(repetition))) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s01",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s02") %>%
  ggplot(aes(norm_timepoint, f0, colour = as.factor(repetition))) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s02",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s04") %>%
  ggplot(aes(norm_timepoint, f0, colour = as.factor(repetition))) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s04",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s05") %>%
  ggplot(aes(norm_timepoint, f0, colour = as.factor(repetition))) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s05",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)

f0 %>%
  filter(speaker == "s06") %>%
  ggplot(aes(norm_timepoint, f0, colour = as.factor(repetition))) +
  facet_wrap(~ sentence) +
  geom_point(alpha = 0.5, size = 0.5) +
  labs(
    title = "s06",
    x = "f0 (Hz)",
    y = "normalised time"
  ) +
  ylim(0, 600)
```

