---
title: "Plot intonation contours"
author: "Stefano Coretta"
date: "03/08/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(emuR)
library(tidyverse)
theme_set(theme_minimal())
library(zoo)
```

# Prep data

## Prepare emuDB

```{r emudb}
db_handle <- load_emuDB("./data/alb-ipa-int_emuDB", verbose = TRUE)
```

```{r f0}
f0_red <- readRDS("./data/dataframes/f0.rds") %>%
  select(token, times_orig) %>%
  separate(token, into = c("session", "bundle"), sep = " ") %>%
  group_by(session, bundle) %>%
  filter(times_orig == min(times_orig) | times_orig == max(times_orig)) %>%
  mutate(
    minmax = ifelse(times_orig == min(times_orig), "t_start", "t_end")
  ) %>%
  pivot_wider(names_from = minmax, values_from = times_orig)

f0 <- readRDS("./data/dataframes/f0.rds")
```


# Get and plot data

```{r get-syl-f0}
syl <- query(db_handle, "SYL =~ .*", calcTimes = T) %>%
  filter(labels != "<p:>")
syl_f0 <- get_trackdata(db_handle, seglist = syl, ssffTrackName = "F0", cut = 0.5) %>%
  rename(time = "times_orig") %>%
  left_join(y = f0_red) %>%
  mutate(
    sentence_duration = t_end - t_start,
    norm_timepoint = (time - t_start) / sentence_duration
  ) %>%
  rename(f0 = "T1", speaker = "session") %>%
  mutate(
    sentence_type = str_sub(bundle, 5),
    sentence = recode(
      sentence_type,
      "broad-focus" = "Lena lau murin.",
      "narrow-focus" = "Lena lau murin, jo lulen.",
      "polar-q" = "A e lau Lena murin?",
      "narrow-focus-q" = "Çfarë lau Lena?"
      )
  )
syl_f0[syl_f0$labels == "tSfa4",]$f0 <- 400
syl <- syl %>%
  left_join(y = f0_red) %>%
  mutate(
    sentence_duration = t_end - t_start,
    start_norm = (start - t_start) / sentence_duration,
    end_norm = (end - end) / sentence_duration
  )
```

```{r int-plot}
f0 %>%
  group_by(token) %>%
  mutate(f0_smooth = c(rep(NA, 10), rollmean(f0, 21), rep(NA, 10))) %>%
  filter(
    repetition == 2,
    speaker == "s01" & sentence_type == "narrow-focus" |
    speaker == "s01" & sentence_type == "polar-q" |
    speaker == "s04" & sentence_type == "broad-focus" |
    speaker == "s04" & sentence_type == "narrow-focus-q"
  ) %>%
  ggplot(aes(norm_timepoint, f0_smooth)) +
  geom_path(aes(colour = speaker), linetype = "dashed") +
  geom_text(data = syl_f0, aes(norm_timepoint, f0, label = labels), nudge_y = 20, size = 4) +
  facet_wrap(. ~ sentence, ncol = 1) +
  labs(
    title = "Smoothed f0 contours",
    caption = "Rolling mean filter, order = 21",
    x = "normalised time",
    y = "f0 (Hz)"
  ) +
  ylim(150, 450) +
  theme(legend.pos = "none") +
  scale_color_brewer(type = "qual")

ggsave("./img/int-plot.png", width = 7, height = 5)
```

