---
title: "Ultrasound"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = here::here())
library(tidyverse)
theme_set(theme_bw())
library(rticulate)
```

# Read data

```{r data}
cols <- c(
  "speaker",
  "rec_date",
  "time",
  "prompt",
  "label"
)

laterals <- read_aaa("./data/ultrasound/laterals-splines.txt", column_names = cols) %>%
  mutate(
    id = as.numeric(as.factor(paste(rec_date, time)))
  ) %>%
  group_by(rec_date) %>%
  mutate(
    time_norm = (time - min(time)) / (max(time) - min(time)),
    prompt = as.factor(prompt)
  ) %>%
  drop_na()
```

# Laterals

```{r lateral-splines-alpha}
laterals %>%
  ggplot(aes(X, Y, group = id, colour = prompt, alpha = time_norm)) +
  geom_path()

ggsave("./img/laterals.png", width = 7, height = 5)
```

```{r laterals-all}
laterals %>%
  ggplot(aes(X, Y, group = id, colour = prompt)) +
  geom_path(alpha = 0.5) +
  labs(
    colour = "lateral",
    x = "back-to-front (mm)", y = "low-to-high (mm)"
  )

ggsave("./img/laterals-all.png", width = 7, height = 5)
```

```{r laterals-gam}
laterals_gam <- polar_gam(
  Y ~
    s(X, by = prompt),
  data = laterals %>% filter(fan_line > 5, fan_line < 40),
  fan_lines = c(15, 20)
)
```

```{r laterals-gam-plot}
plot_polar_smooths(laterals_gam, X, prompt, exclude_random = FALSE)
```

# Vowels

